services:
  - type: web
    name: warranty-claims
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: warranty-claims-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: warranty-claims-redis
          type: redis
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: uploads
      mountPath: /var/data
      sizeGB: 1

  - type: redis
    name: warranty-claims-redis
    ipAllowList: []
    plan: free

databases:
  - name: warranty-claims-db
    databaseName: warranty_claims
    plan: free 